SERVICE_CHOICES = [
    ("local_staycations", "Local staycations"),
    ("beach_holidays", "Beach holidays"),
    ("safaris", "Safaris"),
    ("international_trips", "International trips"),
    ("ticketing", "Ticketing"),
    ("visa_support", "Visa support"),
    ("hotel_bookings", "Hotel bookings"),
    ("ground_transfers", "Ground transfers"),
    ("travel_insurance", "Travel insurance"),
    ("group_trips", "Group trips"),
    ("honeymoons", "Honeymoons"),
    ("corporate_travel", "Corporate travel"),
    ("events", "Events and conferences"),
]

CLIENT_CHOICES = [
    ("local_travelers", "Local travelers"),
    ("international_tourists", "International tourists"),
    ("corporate_clients", "Corporate clients"),
    ("groups", "Groups"),
    ("families", "Families"),
    ("couples", "Couples and honeymooners"),
    ("diaspora", "Diaspora clients"),
    ("schools_churches", "Schools, churches, or chama groups"),
]

PLATFORM_CHOICES = [
    ("whatsapp", "WhatsApp"),
    ("instagram", "Instagram"),
    ("facebook", "Facebook"),
    ("tiktok", "TikTok"),
    ("website", "Website"),
    ("email", "Email"),
    ("google_search", "Google search"),
    ("linkedin", "LinkedIn"),
    ("referrals", "Referrals"),
]

YES_NO_CHOICES = [
    ("yes", "Yes"),
    ("no", "No"),
    ("not_sure", "Not sure"),
]

QUESTIONS = [
    {
        "slug": "basics",
        "eyebrow": "Step 1",
        "title": "Company Basics",
        "intro": "Start with a few details so the response is easy to follow later.",
        "fields": [
            {"name": "company_name", "label": "Company name", "type": "text", "required": True,
             "helper": "The name of the travel company or team filling this in.", "placeholder": "Example: Myriad Travel"},
            {"name": "contact_person", "label": "Main contact person", "type": "text", "required": True,
             "helper": "Share the name of the person I should follow up with after reviewing the answers.", "placeholder": "Full name"},
            {"name": "email", "label": "Best email for follow-up", "type": "email", "required": True,
             "helper": "Use the email where you would like me to send next steps or clarifications.", "placeholder": "name@example.com"},
            {"name": "phone", "label": "Phone or WhatsApp number", "type": "text", "required": False,
             "helper": "Optional, but helpful if WhatsApp is easier for quick clarification.", "placeholder": "+254..."},
        ],
    },
    {
        "slug": "offers",
        "eyebrow": "Step 2",
        "title": "Services And Offers",
        "intro": "This helps me understand what the business sells now, and what should receive more attention.",
        "fields": [
            {"name": "main_services", "label": "What are your main services or packages right now?", "type": "textarea", "required": True,
             "helper": "Start with the services you sell most often. A simple list is okay: safaris, beach holidays, staycations, flights, visa support, hotels, transfers, group trips, honeymoons, corporate travel, retreats, or events.",
             "placeholder": "Example: Safaris, Diani packages, Dubai trips, flight booking, visa support..."},
            {"name": "top_revenue_services", "label": "Which services bring in the most clients or revenue?", "type": "textarea", "required": False,
             "helper": "If exact numbers are not available, just mention the top 2 or 3 services that perform best.",
             "placeholder": "Example: Dubai packages, Diani group trips, Maasai Mara safaris..."},
            {"name": "priority_offers", "label": "Which offers would you like to promote most in the next few weeks or months?", "type": "checkboxes",
             "required": False, "choices": SERVICE_CHOICES,
             "helper": "Choose all that apply. You can also explain special offers in the next question."},
            {"name": "priority_offers_other", "label": "Other offers you want to focus on", "type": "text", "required": False,
             "helper": "Add anything missing from the options above. You can separate several ideas with commas.",
             "placeholder": "Example: medical travel, pilgrimages, sports trips..."},
        ],
    },
    {
        "slug": "clients",
        "eyebrow": "Step 3",
        "title": "Clients And Booking Flow",
        "intro": "This section maps how a client moves from first contact to booking.",
        "fields": [
            {"name": "ideal_clients", "label": "Who is your ideal client?", "type": "checkboxes", "required": False,
             "choices": CLIENT_CHOICES, "helper": "Choose the client groups you serve most, or the ones you want more of."},
            {"name": "ideal_clients_other", "label": "Other client groups", "type": "text", "required": False,
             "helper": "Add any client type that is not listed above.",
             "placeholder": "Example: NGOs, government teams, wedding parties..."},
            {"name": "lead_sources", "label": "How do most clients currently find you?", "type": "textarea", "required": False,
             "helper": "Examples: referrals, WhatsApp, Instagram, Facebook, Google search, TikTok, walk-ins, agents, past clients, or corporate networks.",
             "placeholder": "Where do inquiries usually come from?"},
            {"name": "booking_workflow", "label": "What usually happens from the time a client first contacts you to when they book?", "type": "textarea", "required": True,
             "helper": "Describe the normal steps. For example: client messages on WhatsApp, team shares options, prepares quotation, confirms availability, sends invoice, follows up payment.",
             "placeholder": "Walk me through the process..."},
            {"name": "lead_follow_up", "label": "When someone messages on WhatsApp, social media, email, or the website, who responds and how is the lead followed up?", "type": "textarea", "required": False,
             "helper": "Mention who replies, how fast, and whether follow-ups are tracked anywhere.",
             "placeholder": "Who handles inquiries and follow-ups?"},
            {"name": "quotation_process", "label": "Do you have a standard way of preparing quotations and itineraries, or is each one done from scratch?", "type": "textarea", "required": False,
             "helper": "This helps identify whether templates, pricing sheets, or itinerary formats need to be created.",
             "placeholder": "Explain how quotes and itineraries are currently prepared..."},
        ],
    },
    {
        "slug": "marketing",
        "eyebrow": "Step 4",
        "title": "Marketing And Content",
        "intro": "This helps me understand your current online presence, content process, and what support is needed.",
        "fields": [
            {"name": "content_owner", "label": "Who currently creates posters, captions, videos, itineraries, and other content?", "type": "textarea", "required": False,
             "helper": "Mention whether this is handled internally, by a freelancer, by an agency, or not consistently handled yet.",
             "placeholder": "Who creates content now?"},
            {"name": "active_pages", "label": "Which social media pages are active, and who manages them?", "type": "textarea", "required": False,
             "helper": "Include links or handles where possible, plus who currently posts or responds.",
             "placeholder": "Instagram, Facebook, TikTok, LinkedIn..."},
            {"name": "paid_ads_history", "label": "Have you run paid ads before on Facebook, Instagram, Google, TikTok, or any other platform?", "type": "radio", "required": False,
             "choices": YES_NO_CHOICES, "helper": "Choose the closest answer. You can explain results or challenges in the next field."},
            {"name": "paid_ads_notes", "label": "If you have run ads before, what worked or did not work?", "type": "textarea", "required": False,
             "helper": "Mention budgets, best-performing offers, challenges, leads received, or whether tracking was unclear.",
             "placeholder": "Share anything you remember about past ads..."},
            {"name": "content_focus", "label": "What should content focus on most?", "type": "textarea", "required": False,
             "helper": "Examples: selling packages, educating travelers, showing destinations, showing client experiences, building trust, or promoting seasonal deals.",
             "placeholder": "What should people know, feel, or do after seeing your content?"},
            {"name": "marketing_platforms", "label": "Which platforms matter most for the business right now?", "type": "checkboxes", "required": False,
             "choices": PLATFORM_CHOICES, "helper": "Choose the channels you care about most, even if they are not fully active yet."},
            {"name": "marketing_platforms_other", "label": "Other platforms or channels", "type": "text", "required": False,
             "helper": "Add any other place where clients find you or where you want to grow.",
             "placeholder": "Example: YouTube, agents, exhibitions, TripAdvisor..."},
            {"name": "ad_budget", "label": "For paid ads, what budget are you comfortable starting with per month?", "type": "textarea", "required": False,
             "helper": "A small starting range is okay. For many small travel businesses, KES 5,000 - 25,000 per month can be enough to test which offers bring serious inquiries.",
             "placeholder": "Example: KES 5,000 - 25,000 per month..."},
        ],
    },
    {
        "slug": "systems",
        "eyebrow": "Step 5",
        "title": "Website, Email And Tools",
        "intro": "This section shows what systems already exist and what may need setup, cleanup, or support.",
        "fields": [
            {"name": "email_marketing", "label": "Do you have an email list or any email marketing system in place?", "type": "textarea", "required": False,
             "helper": "Examples: Mailchimp, Brevo, Zoho Campaigns, HubSpot, Gmail contacts, Google Sheets, or no system yet.",
             "placeholder": "What exists for email marketing?"},
            {"name": "client_database", "label": "Do you currently keep client details anywhere?", "type": "textarea", "required": False,
             "helper": "Examples: Excel, Google Sheets, WhatsApp labels, CRM, email contacts, booking software, notebooks, or staff phones.",
             "placeholder": "Where are client details kept?"},
            {"name": "tools_subscriptions", "label": "What tools or subscriptions are you currently paying for?", "type": "textarea", "required": False,
             "helper": "Examples: Canva, website hosting, domain, business email, CRM, booking tools, Meta ads, Google Workspace, accounting tools, or WhatsApp Business.",
             "placeholder": "List any tools, platforms, or subscriptions..."},
            {"name": "account_access", "label": "Do you have access to all important accounts and passwords?", "type": "radio", "required": False,
             "choices": YES_NO_CHOICES, "helper": "This includes website admin, domain, hosting, email, social media, ad accounts, Google Business Profile, Canva, and analytics."},
            {"name": "website_pages_needed", "label": "For your website, what pages or sections would you like included?", "type": "textarea", "required": False,
             "helper": "A simple list is okay. For example: Home, About Us, Safari Bundles or Packages, Destinations, Contact, Testimonials, Blog, Gallery, FAQs, or Corporate Travel.",
             "placeholder": "Example: Home, About Us, Packages, Contact, Testimonials..."},
            {"name": "website_content_help", "label": "Do you already have website content, or would you need help writing it?", "type": "textarea", "required": False,
             "helper": "Mention what is ready and what needs support: company profile, package descriptions, destination text, photos, testimonials, FAQs, blog ideas, or service descriptions.",
             "placeholder": "Example: We have photos and packages, but need help writing the pages..."},
            {"name": "website_project_budget", "label": "What is your initial website project budget?", "type": "textarea", "required": False,
             "helper": "A range is enough for now. This helps match the website scope with what is realistic for design, pages, content, hosting, domain, email setup, and future support.",
             "placeholder": "Example: KES 50,000 - 70,000, or not sure yet..."},
            {"name": "website_updates", "label": "Who currently manages updates on your website or online platforms?", "type": "textarea", "required": False,
             "helper": "This may include packages, prices, photos, blogs, WhatsApp links, inquiry forms, landing pages, or destination pages.",
             "placeholder": "Who updates the website and online pages?"},
            {"name": "website_cleanup", "label": "Are all website offers current, or are there old packages, placeholder content, wrong prices, or pages that need cleaning up?", "type": "textarea", "required": False,
             "helper": "It is okay if some information is outdated. This helps prioritize cleanup.",
             "placeholder": "What needs checking or updating?"},
            {"name": "tech_issues", "label": "What tech issues usually come up in the business?", "type": "textarea", "required": False,
             "helper": "Examples: email problems, website edits, slow site, password access, social media login issues, forms not working, file organization, or team device support.",
             "placeholder": "What tech problems repeat often?"},
        ],
    },
    {
        "slug": "operations",
        "eyebrow": "Step 6",
        "title": "Operations And Assets",
        "intro": "This helps clarify what is ready, what needs organizing, and who approves work.",
        "fields": [
            {"name": "itinerary_assets", "label": "Do you already have ready-made itineraries, packages, rates, brochures, or proposal templates?", "type": "textarea", "required": False,
             "helper": "Mention what exists and where it is stored. For example: Google Drive, WhatsApp, laptops, Canva, printed documents, or website pages.",
             "placeholder": "What sales or itinerary materials are already available?"},
            {"name": "client_info_collected", "label": "For services like visa processing, ticket booking, hotel booking, transfers, and insurance, what information do you normally collect from the client?", "type": "textarea", "required": False,
             "helper": "Examples: passport details, travel dates, destination, budget, rooming list, ID copies, passenger names, ages, or company details.",
             "placeholder": "What details do clients usually submit?"},
            {"name": "brand_assets", "label": "Do you have brand assets ready?", "type": "textarea", "required": False,
             "helper": "Examples: logo files, brand colors, fonts, photos, videos, past posters, company profile, proposal templates, client photos, or testimonials.",
             "placeholder": "What brand and content assets are ready?"},
            {"name": "testimonials", "label": "Do you have repeat clients or past travelers we can use for testimonials, reviews, referrals, and follow-ups?", "type": "textarea", "required": False,
             "helper": "Mention whether you have permission to use photos, names, screenshots, or review text.",
             "placeholder": "What testimonials or client stories can be used?"},
            {"name": "seasonal_offers", "label": "Are there upcoming seasonal offers we should plan early for?", "type": "textarea", "required": False,
             "helper": "Examples: school holidays, Easter, Christmas, Valentine, group trips, migration season, corporate retreats, conferences, or public holidays.",
             "placeholder": "What upcoming offers or dates matter?"},
            {"name": "partnerships", "label": "Are there partnerships or supplier contacts that should be highlighted in marketing?", "type": "textarea", "required": False,
             "helper": "Examples: hotels, resorts, lodges, airlines, conservancies, transport providers, event venues, or tourism associations.",
             "placeholder": "Which partners matter for credibility or offers?"},
            {"name": "corporate_materials", "label": "For corporate clients and events, do you already have a company proposal, rate card, or pitch deck that can be sent quickly?", "type": "textarea", "required": False,
             "helper": "This helps know whether corporate sales material needs to be created or improved.",
             "placeholder": "What corporate materials exist?"},
        ],
    },
    {
        "slug": "priorities",
        "eyebrow": "Step 7",
        "title": "Priorities And Working Together",
        "intro": "Finish with what needs attention first and how success should be measured.",
        "fields": [
            {"name": "urgent_priorities", "label": "What are the most urgent things you want fixed or improved in the first month?", "type": "textarea", "required": True,
             "helper": "List the things that would make the biggest difference quickly. They can be marketing, content, website, systems, sales, or team workflow issues.",
             "placeholder": "Top priorities for the first month..."},
            {"name": "success_30_60_90", "label": "What would make you feel this partnership is working well after 30, 60, or 90 days?", "type": "textarea", "required": True,
             "helper": "Think practically. Examples: more inquiries, better content consistency, cleaner website, faster quotations, working email marketing, organized client database, clearer reports.",
             "placeholder": "Success after 30 days..., 60 days..., 90 days..."},
            {"name": "monthly_reports", "label": "What reports would you like to see monthly?", "type": "textarea", "required": False,
             "helper": "Examples: inquiries, bookings, ad results, social media growth, website visits, email performance, revenue by package, pending follow-ups, or content posted.",
             "placeholder": "What should be reported every month?"},
            {"name": "approvals", "label": "Who will approve content, ads, budgets, offers, and website changes before they go live?", "type": "textarea", "required": False,
             "helper": "Mention names or roles, and whether approvals happen on WhatsApp, email, meetings, or another channel.",
             "placeholder": "Who approves what?"},
            {"name": "ownership_scope", "label": "What work should I be fully responsible for, and what will your team still handle?", "type": "textarea", "required": True,
             "helper": "For example: I can handle website updates, content planning, posters, ads, reports, email marketing, and tech support. Your team may still approve budgets, confirm package prices, provide photos, and handle final client bookings.",
             "placeholder": "What should I handle, and what will your team handle?"},
            {"name": "project_start_timeline", "label": "How soon would you like the project to start?", "type": "textarea", "required": False,
             "helper": "A simple answer is okay: immediately, next week, next month, or add an exact date.",
             "placeholder": "Example: Immediately, next week, or after we agree on scope..."},
            {"name": "extra_notes", "label": "Anything else I should know before we begin?", "type": "textarea", "required": False,
             "helper": "Add any background, concerns, expectations, or context that did not fit above.",
             "placeholder": "Optional notes..."},
        ],
    },
]

for section in QUESTIONS:
    if section["slug"] == "basics":
        continue
    section["fields"].append({
        "name": f"{section['slug']}_anything_else",
        "label": f"Anything else we have left out in {section['title'].lower()}?",
        "type": "textarea",
        "required": False,
        "helper": "You can write any extra thoughts, missing details, concerns, or ideas for this section. If there is nothing else, leave it blank and click Next.",
        "placeholder": "Optional: add anything else we should know for this section...",
    })

FIELD_LOOKUP = {field["name"]: field for section in QUESTIONS for field in section["fields"]}


def choice_label(field, value):
    for option_value, option_label in field.get("choices", []):
        if option_value == value:
            return option_label
    return value
